config/routes.rb
Rails.application.routes.draw do

	patch '/users/:id/jobs/:id/add_contact', to: 'jobs#add_contact', as: 'add_job_contact'
	patch '/users/:id/jobs/:id/add_document', to: 'jobs#add_document', as: 'add_job_document'

	get '/users/:id/jobs/:id/unlink_contact', to: 'jobs#unlink_contact', as: 'unlink_job_contact'
	get '/users/:id/jobs/:id/unlink_document', to: 'jobs#unlink_document', as: 'unlink_job_document'



	patch '/users/:id/tasks/:id/add_contact', to: 'tasks#add_contact', as: 'add_task_contact'
	patch '/users/:id/tasks/:id/add_document', to: 'tasks#add_document', as: 'add_task_document'
	patch '/users/:id/tasks/:id/add_job', to: 'tasks#add_job', as: 'add_task_job'

	get '/users/:id/tasks/:id/unlink_contact', to: 'tasks#unlink_contact', as: 'unlink_task_contact'
	get '/users/:id/tasks/:id/unlink_document', to: 'tasks#unlink_document', as: 'unlink_task_document'
	get '/users/:id/tasks/:id/unlink_job', to: 'tasks#unlink_job', as: 'unlink_task_job'



	get '/users/:id/contacts/:id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
	get '/users/:id/jobs/:id/applied', to: 'jobs#applied', as: 'applied'
	get '/users/:id/tasks/:id/completed', to: 'tasks#completed', as: 'completed'



	get '/users/:id/jobs/:id/next', to: 'jobs#next', as: 'user_job_next'
	get '/users/:id/jobs/:id/previous', to: 'jobs#previous', as: 'user_job_previous'


	get '/users/:id/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'


	get '/jobs/filter', to: 'jobs#filter', as: 'jobs_filter'
	get '/contacts/filter', to: 'contacts#filter', as: 'contacts_filter'	
	get '/tasks/filter', to: 'tasks#filter', as: 'tasks_filter'
	get '/documents/filter', to: 'documents#filter', as: 'documents_filter'

	get '/signin' => 'sessions#new'
	post '/signin' => 'sessions#create'
	delete '/logout' => 'sessions#destroy'

	resources :users do 
		resources :contacts 
		resources :documents
		resources :jobs
		resources :tasks
	end


	root "static_pages#home"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	belongs_to :contact, optional: true
	belongs_to :job, optional: true
	belongs_to :document, optional: true

	validates_associated :user
	
	scope :filtered_task, -> (substring) { where("title LIKE ? ", "%#{substring}%")}
	
	scope :completed_false, -> { where('completed = ?',false) }
	scope :completed_true, -> { where('completed = ?',true) }

	scope :overdue, -> { where('due_date < ?', DateTime.now.end_of_day) }
	scope :upcoming, -> { where('due_date >= ?', DateTime.now.beginning_of_day) }
	scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, except: [:index, :filter, :new, :create]

	def index 
		@tasks = current_user.tasks 
		@tasks_sorted = @tasks.sort_by &:date_due
		respond_to do |format|
	      format.html { render :index }
	      format.json { render json: @tasks_sorted, status: 200 }
	    end
	end


	def filter
		@filtered_tasks = current_user.tasks.filtered_task(params[:q])
		respond_to do |format|
			format.json { render json: { html: render_to_string("tasks/_filtered_tasks.html.erb", layout: false, locals: { filtered_tasks: @filtered_tasks })} }
		end
	end



	def completed
		completedStr = (params[:q])
		completedBool = completedStr.to_s == "true"
		@task.completed = completedBool
		@task.save
		flash[:notice] = "Task status changed"
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @task, status: 200 }
	    end
	end


	def add_contact
		c_id = params[:task][:contact_id]		
		contact = Contact.find(c_id)
		if !contact.tasks.include?(@task)
			contact.tasks << @task
			contact.save
		end
	end	


	def add_document
		d_id = params[:task][:document_id]
		document = Document.find(d_id)
		if !document.tasks.include?(@task)
			document.tasks << @task
			document.save
		end
	end	


	def add_job
		j_id = params[:task][:job_id]
		job = Job.find(j_id)
		if !job.tasks.include?(@task)
			job.tasks << @task
			job.save
		end
	end	





	def unlink_contact
		c = @task.contact 
		c.tasks.delete(@task)
		@task.contact_id = nil 
		c.save
		@task.save

		flash[:notice] = "Contact removed"
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @task, status: 200 }
	    end
	end		

	def unlink_document
		d = @task.document 
		d.tasks.delete(@task)
		@task.document_id = nil 
		d.save
		@task.save
		flash[:notice] = "Document removed"
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @task, status: 200 }
	    end
	end		

	def unlink_job
		j = @task.job 
		j.tasks.delete(@task)
		@task.job_id = nil 
		j.save
		@task.save
		flash[:notice] = "Job removed"
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @task, status: 200 }
	    end
	end	









	def new 
		@task = Task.new(user: current_user)
		@tasks = current_user.tasks
	end


	def create
		@task = Task.create(task_params)
		@task.user = current_user
		@task.save 
		respond_to do |format|
			format.json { render json: { html: render_to_string("tasks/_task.html.erb", layout: false, locals: { task: @task })} }
		end
	end


	def show
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @task, status: 200 }
	    end
	end


	def edit
	end


	def update
	    @task.update(task_params)
	    flash[:notice] = "Task updated"
	    redirect_to user_task_path(@task.user, @task)
	end


	def destroy
		@task.destroy
		flash[:notice] = "Task destroyed"
	    redirect_to new_user_task_path(current_user)
	end




	private 


	def task_params
		params.require(:task).permit(:title, :description, :doctype, :due_date, :completed)
	end


	def set_task
		@task = Task.find(params[:id])
	end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_basic_task.html.erb
<h1><%= @contact.last_name %></h1>
<p><%= @task %></p>
<h3><%= link_to @task.title, user_task_path(@task.user, @task), :class => "task-item" %></h3>

app/views/tasks/_filtered_tasks.html.erb
<% filtered_tasks.each do |task| %>
	<h3><%= link_to "#{task.title} #{format_date(task.due_date)}", user_task_path(task.user, task)%></h3>
<% end %>

app/views/tasks/_form.html.erb
	
<%= form_for [@task.user, @task] do |f| %>

    <div class="field">
        <%= f.label :title, "Title" %><br>
        <%= f.text_field :title, id: "title", :required => true  %>
    </div>

    <div class="field">
        <%= f.label :due_date %><br>
        <%= f.date_field :due_date, id: "due-date" %>
    </div>            

    <div class="field">
        <%= f.label :description, "Description" %><br>
        <%= f.text_area :description, id: "description", rows: 10 %>
    </div>

    <div class="actions">
        <%= f.submit "SAVE" %>
    </div>

<% end %>

   

app/views/tasks/_task.html.erb
<% if task.completed != true %>
	<h3><%= link_to "<li>#{task.title} - #{format_date(task.due_date)}</li><br>".html_safe, user_task_path(task.user, task), :class => "bullet-item" %></h3>

<% else %>
	<h3><i class="material-icons">check</i><%= link_to "#{task.title} - #{format_date(task.due_date)}<br>".html_safe, user_task_path(task.user, task), :class => "check-item" %></h3><br>
<% end %>

app/views/tasks/edit.html.erb
<div class='wrapper'>
	<%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<h1>tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date Posted</th>
    <th>Completed</th>
    <th></th>
    <th></th>
  </tr>

  <% @tasks.each do |task| %>
	  <tr>
	    <td><%= link_to task.title, user_task_path(task.user, task) %></td>
	    <td><%= task.description %></td>
	    <td><%= convert_date(task.due_date) %></td>
	    <td>Completed</td>
	    <td><%= link_to "Edit", edit_user_task_path(task.user, task) %></td>
	    <td><%= link_to "Delete", user_task_path(task.user, task), :method => :delete %></td>
	  </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<div id='new-task-wrapper'>

	<div class='column-3'>
		<h1>COMPLETED TASKS</h1>
		<div id='completed-tasks-list'></div>
	    	<%= render partial: "task", collection: @tasks.completed_true || "No Tasks"%>
	    </div>
	</div> <!-- close column -->

	<div class='column-3'>
	    <h1>UPCOMING TASKS</h1>
	    <div id='task-list'>
	    	<%= render partial: "task", collection: @tasks.completed_false.order('due_date ASC') || "No Tasks"%>
	    </div>
	</div> <!-- close column -->

	<div class='column-3'>
		<h1>Add Task</h1>
		<%= render 'form' %>
	</div> <!-- close column -->

</div>  <!-- close wrapper -->





<script type="text/javascript" charset="utf-8">


$("form").on('submit', function (e) {
	e.preventDefault()
	var $form = $(this)
	var action = $form.attr('action')
	var params = $form.serialize()

	$.ajax({
		url: action,
		data: params,
		datatype: 'json',
		method: 'POST', 
	    success: function (data) {
			alert('success') 
			$("#task-list").append(data.html),
			$("#new_task")[0].reset();
		},
		error: function (data) {
			alert('something went wrong') }
	})
})






</script>

app/views/tasks/show.html.erb
<div id='task-show-wrapper'>
    <div class='user-id' data-id="<%= @task.user.id %>"></div>
    <div class='task-id' data-id="<%= @task.id %>"></div>

    <div id='top'>
        <h1><%= @task.title %></h1>
        <div class='details-container'>
        	<h3><%= @task.description %></h3>
            <div id='task-due-date'><h3>DUE DATE: <%= format_date(@task.due_date) %></h3></div>
            <div id='task-completed-string'></div>
            <div id='add-completed'></div>
            <div id='completed-btn'></div>
            <td><%= link_to "Edit", edit_user_task_path(@task.user, @task) %></td>
            <td><%= link_to "Delete", user_task_path(@task.user, @task), :method => :delete %></td>
        </div>
    </div> <!-- close top -->

    <div id='results'></div>

    <div id='mid'>
        <div id='docs' class='links-col'>
            <% if @task.document != nil %>   
                <h2 class='linked-item'>LINKED DOCUMENT</h2>
                <h3><%= link_to @task.document.title, user_document_path(@task.user, @task.document) %></h3><br>
                <button class='unlink-button' id='unlink-document'>Unlink Document</button>
            <% else %>
                <h2 class='unlinked-item'>No linked Document</h2>
                <%= render 'documents/document_task_dropdown' %>
            <% end %>
        </div> <!-- close column -->

        <div id='contacts' class='links-col'>
            <% if @task.contact != nil %>   
                <h2 class='linked-item'>LINKED CONTACT </h2>

                <div id='task-contacts'>
                    <h3><%= link_to "#{formatted_name(@task.contact)}", user_contact_path(@task.user, @task.contact) %></h3><br>
                </div>
                <button class='unlink-button' id='unlink-contact'>Unlink Contact</button>
            <% else %>
                <h2 class='unlinked-item'>No linked contact</h2>
                <%= render 'contacts/contact_task_dropdown' %>
            <% end %>
        </div> <!-- close column -->


        <div id='Jobs' class='links-col'>
            <% if @task.job != nil %>   
                <h2 class='linked-item'>LINKED JOB</h2>
                <h3><%= link_to @task.job.company, user_job_path(@task.user, @task.job) %></h3><br>
                <button class='unlink-button' id='unlink-job'>Unlink Job</button>
            <% else %>
                <h2 class='unlinked-item'>No linked job</h2>
                <%= render 'jobs/job_task_dropdown' %>
            <% end %>
        </div> <!-- close column -->
    </div> <!-- close mid -->

</div> <!-- close wrapper -->




<script>


$(document).ready(function () {
    user_id = $(".user-id").data("id")
    task_id = $(".task-id").data("id")

    $.get(`/users/${user_id}/tasks/${task_id}.json`, function(data) {
        task = new Task(data, user_id)
        displayTaskDetails(task)
        linkTaskContact()
        linkTaskDocument()
        linkTaskJob()
        buttonCompleted(task)
        unlinkContact()
        unlinkDocument()
        unlinkJob()

    });
    
})



const buttonCompleted = function (task) {
    $('#completed-btn').on('click', function() {
        $.get(`/users/${user_id}/tasks/${task_id}/completed?q=${!task.completed}`, function(data) {
            $('#task-completed-string').empty()
            $('#completed-btn').empty()
            $('#task-completed-string').append(task.completedString(!task.completed))
            $('#completed-btn').append(task.completedButton(!task.completed))
        })
    })
}


const displayTaskDetails = function(task) {
    $('#task-completed-string').append(task.completedString())
    $('#completed-btn').append(task.completedButton())
}





const linkTaskContact = function() {
    $('#btn-add-contact').on('click', function(e) {
        e.preventDefault()
        var form = $('#add-contact')

        var action = form.attr('action')
        var c_id = form.serialize()


        $.ajax({url: `/users/${user_id}/tasks/${task_id}/add_contact`, 
            data: c_id, 
            type: "PATCH", 
            success: function (data) {
                alert('success') 
                $('#task-contacts').append(`<a href="/users/2/contacts/11">Rachel  Maddow</a>`)
            },
            error: function (data) {
                alert('no success') }

        })
    })
}


const linkTaskDocument = function() {
    $('#btn-add-document').on('click', function(e) {
        e.preventDefault()
        var form = $('#add-document')
        var action = form.attr('action') //necessary?
        var d_id = form.serialize()

        $.ajax({url: `/users/${user_id}/tasks/${task_id}/add_document`, 
            data: d_id, 
            type: "PATCH", 
            success: function (data) {
                console.log('data')
                console.log(data)
                alert('success') },
            error: function (data) {
                alert('no success') }
        })
    })
}


const linkTaskJob = function() {
    let jobId = $('#task-job-ids')
    $('#btn-add-job').on('click', function(e) {
        e.preventDefault()
        var form = $('#add-job')
        var action = form.attr('action')
        var j_id = form.serialize()

        $.ajax({url: `/users/${user_id}/tasks/${task_id}/add_job`, 
            data: j_id, 
            type: "PATCH", 
            success: function (data) {
                console.log('data')
                console.log(data)
                alert('success') },
            error: function (data) {
                alert('no success') }
        })
    })
}







const unlinkContact = function (task) {
    $('#unlink-contact').on('click', function() {
        $.get(`/users/${user_id}/tasks/${task_id}/unlink_contact`, function(data) {
            console.log(data)
        })
    })
}


const unlinkDocument = function (task) {
    $('#unlink-document').on('click', function() {
        $.get(`/users/${user_id}/tasks/${task_id}/unlink_document`, function(data) {
            console.log(data)
        })
    })
}

const unlinkJob = function (task) {
    $('#unlink-job').on('click', function() {
        $.get(`/users/${user_id}/tasks/${task_id}/unlink_job`, function(data) {
            console.log(data)
        })
    })
}




</script>