config/routes.rb
Rails.application.routes.draw do

	patch '/users/:id/jobs/:id/add_contact', to: 'jobs#add_contact', as: 'add_job_contact'
	patch '/users/:id/jobs/:id/add_document', to: 'jobs#add_document', as: 'add_job_document'

	get '/users/:id/jobs/:id/unlink_contact', to: 'jobs#unlink_contact', as: 'unlink_job_contact'
	get '/users/:id/jobs/:id/unlink_document', to: 'jobs#unlink_document', as: 'unlink_job_document'



	patch '/users/:id/tasks/:id/add_contact', to: 'tasks#add_contact', as: 'add_task_contact'
	patch '/users/:id/tasks/:id/add_document', to: 'tasks#add_document', as: 'add_task_document'
	patch '/users/:id/tasks/:id/add_job', to: 'tasks#add_job', as: 'add_task_job'

	get '/users/:id/tasks/:id/unlink_contact', to: 'tasks#unlink_contact', as: 'unlink_task_contact'
	get '/users/:id/tasks/:id/unlink_document', to: 'tasks#unlink_document', as: 'unlink_task_document'
	get '/users/:id/tasks/:id/unlink_job', to: 'tasks#unlink_job', as: 'unlink_task_job'



	get '/users/:id/contacts/:id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
	get '/users/:id/jobs/:id/applied', to: 'jobs#applied', as: 'applied'
	get '/users/:id/tasks/:id/completed', to: 'tasks#completed', as: 'completed'



	get '/users/:id/jobs/:id/next', to: 'jobs#next', as: 'user_job_next'
	get '/users/:id/jobs/:id/previous', to: 'jobs#previous', as: 'user_job_previous'


	get '/users/:id/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'


	get '/jobs/filter', to: 'jobs#filter', as: 'jobs_filter'
	get '/contacts/filter', to: 'contacts#filter', as: 'contacts_filter'	
	get '/tasks/filter', to: 'tasks#filter', as: 'tasks_filter'
	get '/documents/filter', to: 'documents#filter', as: 'documents_filter'

	get '/signin' => 'sessions#new'
	post '/signin' => 'sessions#create'
	delete '/logout' => 'sessions#destroy'

	resources :users do 
		resources :contacts 
		resources :documents
		resources :jobs
		resources :tasks
	end


	root "static_pages#home"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
	has_many :job_contacts
	has_many :jobs, through: :job_contacts
	has_many :tasks

	validates_associated :user

	scope :filtered_contact, -> (substring) { where("last_name LIKE ? OR first_name LIKE ?", "%#{substring}%", "%#{substring}%")}
	scope :is_reference, -> { where('reference = ?',true) }
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
	has_many :job_contacts
	has_many :contacts, through: :job_contacts
	has_many :job_documents
	has_many :documents, through: :job_documents
	has_many :tasks

	validates_associated :user

	scope :filtered_job, -> (substring) { where("company LIKE ? OR position LIKE ?", "%#{substring}%", "%#{substring}%") }

	# scope :applied, -> { where("applied = ? ", true) }


	def next
		join_query = "LEFT OUTER JOIN users ON user_id = users.id"
		where_query = "jobs.id > ? AND jobs.user_id = ?"

		job = Job.joins(join_query).where(where_query, self.id, self.user_id).first 
		return job ||= Job.find_by(:user_id => self.user_id)
	end


	def previous
		join_query = "LEFT OUTER JOIN users ON user_id = users.id"
		where_query = "jobs.id > ? AND jobs.user_id = ?"

		job = Job.joins(join_query).where(where_query, self.id, self.user_id).first 
		return job ||= Job.find_by(:user_id => self.user_id) 
	end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :set_contact, only: [:show, :edit, :update, :destroy, :add_reference]

	def index 
		@contacts = current_user.contacts
		respond_to do |format|
	      format.html { render :index }
	      format.json { render json: @contacts, status: 200 }
	    end
	end


	def sort  #THIS IS BEING READ AS A SHOW PAGE
		@contacts = current_user.contacts
		@contacts_sorted = @contacts.sort_by &:last_name
		respond_to do |format|
	      # format.html { render :index }
	    	format.json { render json: @contacts_sorted, status: 200 }
			# format.json { render json: { html: render_to_string("contacts/_contact.html.erb", layout: false, locals: { contacts_sorted: @contacts_sorted })} }

	    end
	end


	


	def filter
		@filtered_contacts = current_user.contacts.filtered_contact(params[:q])
		respond_to do |format|
			format.json { render json: { html: render_to_string("contacts/_filtered_contacts.html.erb", layout: false, locals: { filtered_contacts: @filtered_contacts })} }
		end
	end


	def add_reference
		refStr= (params[:q])
		refBool = refStr.to_s == "true"
		@contact.reference = refBool
		flash[:notice] = "Reference status has changed"
		@contact.save
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @contact, status: 200 }
	    end
	end


	def new 
		@contact = Contact.new(user: current_user)
		@contacts = current_user.contacts
	end


	def create
		@contact = Contact.create(contact_params)
		@contact.user = current_user
		@contact.save 

		respond_to do |format|
			format.json { render json: { html: render_to_string("contacts/_contact.html.erb", layout: false, locals: { contact: @contact })} }
		end
	end


	def show
		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @contact, status: 200 }
	    end
	end


	def edit
	end


	def update
		flash[:notice] = "Contact updated"
	    @contact.update(contact_params)
	    redirect_to user_contact_path(@contact.user, @contact)
	end


	def destroy
		flash[:notice] = "Contact destroyed"
		@contact.destroy
		redirect_to new_user_contact_path(current_user)
	end



	private 


	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :workplace, :linkedin, :phone, :email, :reference)
	end


	def set_contact
		@contact = Contact.find(params[:id])
	end



end

app/helpers/contacts_helper.rb
module ContactsHelper


	def formatted_name(contact)
		return ("#{contact.first_name} #{contact.last_name}").titlecase
	end

end

app/views/contacts/_contact.html.erb
<h3 class='list-items'><%= link_to "<li>#{contact.first_name} #{contact.last_name}</li><br>".html_safe, user_contact_path(contact.user, contact), :class => 'bullet-item' %></h3>

app/views/contacts/_contact_dropdown.html.erb
	

<%= form_for [@job.user, @job], :url => user_job_path(@job.user, @job), :html => {:id => "add-contact", :method => :post} do |f| %>

	<p><%= f.collection_select :contact_ids, @job.user.contacts, :id, :last_name, {:include_blank => 'choose contact'} %></p>	

	<%= f.submit "Link Contact", {id: 'btn-add-contact'} %>

<% end %>

app/views/contacts/_contact_task_dropdown.html.erb
<%= form_for [@task.user, @task], :url => user_task_path(@task.user, @task), :html => {:id => "add-contact", :method => :post} do |f| %>

	<p><%= f.collection_select :contact_id, @task.user.contacts, :id, :last_name, {:include_blank => 'choose contact'} %></p>	

	<%= f.submit "Link Contact", {id: 'btn-add-contact'} %>

<% end %>

app/views/contacts/_filtered_contacts.html.erb
<% filtered_contacts.each do |contact| %>
	<h3><%= link_to "#{formatted_name(contact)}", user_contact_path(contact.user, contact)%></h3>
<% end %>

app/views/contacts/_form.html.erb
	
<%= form_for [@contact.user, @contact] do |f| %>

    <div class="field">
        <%= f.label :first_name, "First Name", :required => true  %><br>
        <%= f.text_field :first_name, id: "first-name" %>
    </div>

    <div class="field">
        <%= f.label :last_name, "Last Name" %><br>
        <%= f.text_field :last_name, id: "last-name", :required => true %>
    </div>

    <div class="field">
        <%= f.label :workplace %><br>
        <%= f.text_field :workplace, id: "workplace" %>
    </div>            

    <div class="field">
        <%= f.label :phone %><br>
        <%= f.text_field :phone, id: "phone" %>
    </div>

    <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, id: "email" %>
    </div>            


    <div class="actions">
        <%= f.submit "SAVE" %>
    </div>

<% end %>

   

app/views/contacts/index.html.erb
<h1>contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Workplace</th>
    <th>Phone</th>
    <th>Email</th>
    <th>LinkedIn</th>
    <th></th>
    <th></th>
  </tr>
  
  <% @contacts.each do |contact| %>
	  <tr>
	  	<% c_name = "#{contact.first_name}  #{contact.last_name}" %>

	    <td><%= link_to c_name, user_contact_path(contact.user, contact) %></td>
	    <td><%= contact.workplace %></td>
	    <td><%= contact.phone %></td>
	    <td><%= contact.email %></td>
	    <td><%= contact.linkedin %></td>
	    <td><%= link_to "Edit", edit_user_contact_path(contact.user, contact) %></td>
	    <td><%= link_to "Delete", user_contact_path(contact.user, contact), :method => :delete %></td>
	  </tr>
  <% end %>

</table>

	

app/views/contacts/new.html.erb
<div id='contact-new-page'>
	<div class='user-id' data-id="<%= current_user.id %>"></div>

	<div class="column-3">
		<h1>References</h1>
		<%= render partial: "contact", collection: @contacts.is_reference || "No Contacts"%>
	</div> <!--close column -->

	<div class="column-3">
	    <h1>Contacts</h1>
	    <button id="contacts-sort">First Name</button>
	    <button id="contacts-sort-2">Last Name</button>
		<div id='contact-list'>
		    <%= render partial: "contact", collection: @contacts || "No Contacts"%>
	    </div> <!--close column -->
	</div>

	<div class="column-3">
		<h1>Add Contact</h1>
		<%= render 'form' %>
	</div> <!--close column -->

</div> <!--close page -->






<script type="text/javascript" charset="utf-8">


$(document).ready(function () {
	user_id = $(".user-id").data("id")
	buttonSort1()
	buttonSort2()
})



$("form").on('submit', function (e) {
	e.preventDefault()
	var $form = $(this)
	var action = $form.attr('action')
	var params = $form.serialize()

	$.ajax({
		url: action,
		data: params,
		datatype: 'json',
		method: 'POST', 
	    success: function (data) {
			alert('success') 
			$("#contact-list").append(data.html),
			$("#new_contact")[0].reset();
		},
		error: function (data) {
			alert('something went wrong') }
	})
})



// SORT CONTACTS W/O REQUEST
const buttonSort1 = function() {
	$('#contacts-sort').on('click', function() {
		let $cList = $( "#contact-list .list-items" ).toArray().map((li) => { 
			return `<h3 class="list-items">${li.innerHTML}</h3>`
		})
		$($("#contact-list .list-items" )).remove()
		let $sorted = sortContacts($cList).join('')
		$('#contact-list').append($sorted)
	})
}

const sortContacts = function (c_list) {
	return c_list.sort(function (a, b) {
		let reg = /<li>(.*?)</
		if ( a.match(reg)[0] < b.match(reg)[0] ) return -1;
		if ( a.match(reg)[0] > b.match(reg)[0] ) return 1;
		return 0;
	})
}


// SORT CONTACTS W/ GET REQUEST
const buttonSort2 = function() {
	$('#contacts-sort-2').on('click', function() {
		$.get(`/users/${user_id}/contacts/sort`, function(data) {
			$($("#contact-list .list-items" )).remove()
		    jQuery(data).each(function(i, contact){
		        let c = new Contact(contact, user_id)
		        $("#contact-list").append(c.formatBulletItem())
		    })
        })
	})
}




</script>

app/views/contacts/show.html.erb
<div id='contact-show-container'>
	<div class='user-id' data-id="<%= @contact.user.id %>"></div>
	<div class='contact-id' data-id="<%= @contact.id %>"></div>

	<div id='top'>
		<h1><%= @contact.first_name %> <%= @contact.last_name %> - <%= @contact.workplace %></h1>
		<div class='details-container'>
			<div><h3><%= @contact.email %></h3></div>
			<div><h3><%= @contact.phone %></h3></div>
			<div id='contact_reference'></div>
			<div id='reference-btn'></div>
		    <td><%= link_to "Edit", edit_user_contact_path(@contact.user, @contact) %></td>
		    <td><%= link_to "Delete", user_contact_path(@contact.user, @contact), :method => :delete %></td>
		</div>
	</div> <!-- close top -->

	<div id='bottom'>  
	    <div id='jobs' class='links-col-50 left-col-50'>
	        <h2>LINKED JOBS</h2>
	        <div class='linked-items'>
	            <% if @contact.jobs.length > 0 %>
	                <%= render partial: "jobs/job", collection: @contact.jobs || "No Linked Jobs" %>
	            <% else %>
	                <h3><%= link_to '* Link This Contact To A Job', user_jobs_path(@contact.user) %></h3>
	            <% end %>
	        </div>
	    </div> <!-- close column -->

	    <div id='tasks' class='links-col-50 right-col-50'>
	        <h2>TASKS</h2>
	        <div class='linked-items'>
	            <% if @contact.tasks.length > 0 %>
	                <%= render partial: "tasks/task", collection: @contact.tasks || "No Linked Tasks" %>
	            <% else %>
	                <h3><%= link_to '* Link This Contact To A Task', user_jobs_path(@contact.user) %></h3>
	            <% end %>
	        </div>
	    </div> <!-- close column -->
	</div> <!-- close bottom -->

</div> <!-- close wrapper -->






<script>



$(document).ready(function () {
	user_id = $(".user-id").data("id")
	contact_id = $(".contact-id").data("id")

	$.get(`/users/${user_id}/contacts/${contact_id}.json`, function(data) {
		contact = new Contact(data, user_id)
	    displayRefDetails(contact)
		buttonRefFunc(contact)

	});
})



const buttonRefFunc = function(contact) {
	$('#add-reference').on('click', function() {
	    $.get(`/users/${user_id}/contacts/${contact_id}/add_reference?q=${!contact.reference}`, function(data) {
	    	$('#contact_reference').empty()
	    	$('#reference-btn').empty()
			$('#contact_reference').append(contact.referenceString(!contact.reference))
			$('#reference-btn').append(contact.referenceButton(!contact.reference))
	    })
	})
}



const displayRefDetails = function (contact) {
	$('#contact_reference').append(contact.referenceString())
	$('#reference-btn').append(contact.referenceButton())
}




</script>