config/routes.rb
Rails.application.routes.draw do

	patch '/users/:id/jobs/:id/add_contact', to: 'jobs#add_contact', as: 'add_job_contact'
	patch '/users/:id/jobs/:id/add_document', to: 'jobs#add_document', as: 'add_job_document'

	get '/users/:id/jobs/:id/unlink_contact', to: 'jobs#unlink_contact', as: 'unlink_job_contact'
	get '/users/:id/jobs/:id/unlink_document', to: 'jobs#unlink_document', as: 'unlink_job_document'



	patch '/users/:id/tasks/:id/add_contact', to: 'tasks#add_contact', as: 'add_task_contact'
	patch '/users/:id/tasks/:id/add_document', to: 'tasks#add_document', as: 'add_task_document'
	patch '/users/:id/tasks/:id/add_job', to: 'tasks#add_job', as: 'add_task_job'

	get '/users/:id/tasks/:id/unlink_contact', to: 'tasks#unlink_contact', as: 'unlink_task_contact'
	get '/users/:id/tasks/:id/unlink_document', to: 'tasks#unlink_document', as: 'unlink_task_document'
	get '/users/:id/tasks/:id/unlink_job', to: 'tasks#unlink_job', as: 'unlink_task_job'



	get '/users/:id/contacts/:id/add_reference', to: 'contacts#add_reference', as: 'add_reference'
	get '/users/:id/jobs/:id/applied', to: 'jobs#applied', as: 'applied'
	get '/users/:id/tasks/:id/completed', to: 'tasks#completed', as: 'completed'



	get '/users/:id/jobs/:id/next', to: 'jobs#next', as: 'user_job_next'
	get '/users/:id/jobs/:id/previous', to: 'jobs#previous', as: 'user_job_previous'


	get '/users/:id/contacts/sort', to: 'contacts#sort', as: 'contacts_sort'


	get '/jobs/filter', to: 'jobs#filter', as: 'jobs_filter'
	get '/contacts/filter', to: 'contacts#filter', as: 'contacts_filter'	
	get '/tasks/filter', to: 'tasks#filter', as: 'tasks_filter'
	get '/documents/filter', to: 'documents#filter', as: 'documents_filter'

	get '/signin' => 'sessions#new'
	post '/signin' => 'sessions#create'
	delete '/logout' => 'sessions#destroy'

	resources :users do 
		resources :contacts 
		resources :documents
		resources :jobs
		resources :tasks
	end


	root "static_pages#home"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
	belongs_to :user
	has_many :tasks
	has_many :job_documents
	has_many :jobs, through: :job_documents

	validates_associated :user

	scope :filtered_document, -> (substring) { where("title LIKE ? ", "%#{substring}%")}

end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
	has_many :job_contacts
	has_many :contacts, through: :job_contacts
	has_many :job_documents
	has_many :documents, through: :job_documents
	has_many :tasks

	validates_associated :user

	scope :filtered_job, -> (substring) { where("company LIKE ? OR position LIKE ?", "%#{substring}%", "%#{substring}%") }

	# scope :applied, -> { where("applied = ? ", true) }


	def next
		join_query = "LEFT OUTER JOIN users ON user_id = users.id"
		where_query = "jobs.id > ? AND jobs.user_id = ?"

		job = Job.joins(join_query).where(where_query, self.id, self.user_id).first 
		return job ||= Job.find_by(:user_id => self.user_id)
	end


	def previous
		join_query = "LEFT OUTER JOIN users ON user_id = users.id"
		where_query = "jobs.id > ? AND jobs.user_id = ?"

		job = Job.joins(join_query).where(where_query, self.id, self.user_id).first 
		return job ||= Job.find_by(:user_id => self.user_id) 
	end


end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :set_document, only: [:show, :edit, :update, :destroy] 


	def index 
		@document = Document.all
		respond_to do |format|
			format.html { render :index }
			format.json { render json: @document, status: 200 }
		end
	end


	def filter
		@filtered_documents = current_user.documents.filtered_document(params[:q])
		respond_to do |format|
			format.json { render json: { html: render_to_string("documents/_filtered_documents.html.erb", layout: false, locals: { filtered_documents: @filtered_documents })} }
		end
	end


	def new 
		@document = Document.new(user: current_user)
		@documents = current_user.documents
	end


	def create
		@document = Document.create(document_params)
		@document.user = current_user
		@document.save 
		respond_to do |format|
			format.json { render json: { html: render_to_string("documents/_document.html.erb", layout: false, locals: { document: @document })} }
		end
	end


	def show
		@document = Document.find_by(:id => params[:id], :user_id => current_user.id)
		respond_to do |format|
			format.html { render :show }
			format.json { render json: @document, status: 200 }
		end
	end


	def edit
	end


	def update
		flash[:notice] = "Document updated"
	    @document.update(document_params)
	    redirect_to user_document_path(@document.user, @document)
	end


	def destroy
		flash[:notice] = "Document destroyed"
		@document.destroy
		redirect_to new_user_document_path(@document.user)
	end



	private 


	def document_params
		params.require(:document).permit(:title, :url, :description, :doctype)
	end


	def set_document 
		@document = Document.find(params[:id])
	end




end

app/helpers/documents_helper.rb
module DocumentsHelper


	def groupDoctype(documents) 
		return documents.group_by(&:doctype)
	end

end

app/views/documents/_document.html.erb
<h3><%= link_to "<li>#{document.title}</li><br>".html_safe, user_document_path(document.user, document), :class => "bullet-item" %></h3>

app/views/documents/_document_dropdown.html.erb
<%= form_for [@job.user, @job], :url => user_job_path(@job.user, @job), :html => {:id => "add-document", :method => :post} do |f| %>

	<p><%= f.collection_select :document_ids, @job.user.documents, :id, :title, {:include_blank => 'choose document'} %></p>	

	<%= f.submit "Link Document", {id: 'btn-add-document'} %>

<% end %>

app/views/documents/_document_task_dropdown.html.erb
<%= form_for [@task.user, @task], :url => user_task_path(@task.user, @task), :html => {:id => "add-document", :method => :post} do |f| %>

	<p><%= f.collection_select :document_id, @task.user.documents, :id, :title, {:include_blank => 'choose document'} %></p>	

	<%= f.submit "Link Document", {id: 'btn-add-document'} %>

<% end %>

app/views/documents/_filtered_documents.html.erb
<% filtered_documents.each do |document| %>
	<h3><%= link_to document.title, user_document_path(document.user, document)%></h3>
<% end %>

app/views/documents/_form.html.erb
<%= form_for [@document.user, @document] do |f| %>

	<div class='field'>
		<%= f.label :title, "Title" %><br>
		<%= f.text_field :title, id: 'title', :required => true  %>
	</div>

	<div class='field'>
		<%= f.label :description, "Description" %><br>
		<%= f.text_field :description, id: 'description' %>
	</div>

	<div class='field'>
		<%= f.label :doctype, "Doctype" %><br>
		<%= f.select :doctype, [ 'Resume','Cover Letter','Correspondence', 'Examples', 'Other' ], :prompt => 'Select One', :required => true %>
	</div>

	<div class='field'>
		<%= f.label :url, "Link" %><br>
		<%= f.text_field :url, id: 'url' %>
	</div>

	<div class='actions'>
		<%= f.submit "SAVE" %>
	</div>

<% end %>

app/views/documents/edit.html.erb
<div class='wrapper'>
	<%= render 'form' %>
</div>

app/views/documents/index.html.erb
<h1>Documents</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

  <% @documents.each do |document| %>
	  <tr>
	    <td><%= link_to document.description, user_document_path(document.user, document) %></td>
	    <td>document</td>

	    <td><%= link_to "Edit", edit_user_document_path(document.user, document) %></td>
	    <td><%= link_to "Delete", user_document_path(document.user, document), :method => :delete %></td>
	  </tr>
  <% end %>

</table>

	

app/views/documents/new.html.erb
<div id='new-document-wrapper'>

	<div class='column-3'>
		<% if @documents.length > 0 %>
			<% groupDoctype(@documents).each do |d| %>
				<h1 class='doctype-grp'><%= d[0].pluralize(2) %></h1>
				<% d[1].each do |doc| %>
					<h3><%= link_to "<li>#{doc.title}</li><br>".html_safe, user_document_path(doc.user, doc), :class => "bullet-item" %></h3>
				<% end %> 
			<% end %>
		<% else %>
			<h1>DOCUMENTS BY TYPE</h1>
		<% end %>
	</div> <!-- close column -->

	<div class='column-3'>
	    <h1>All Documents</h1>
		<div id='document-list'>
		    <%= render partial: "document", collection: @documents || "No Documents"%>
	    </div>
	</div> <!-- close column -->

	<div class='column-3'>
		<h1>Add Document</h1>
		<%= render 'form' %>
	</div> <!-- close column -->

</div> <!-- close wrapper -->






<script type="text/javascript" charset="utf-8">



$("form").on('submit', function (e) {

	e.preventDefault()
	var $form = $(this)
	var action = $form.attr('action')
	var params = $form.serialize()


	$.ajax({
		url: action,
		data: params,
		datatype: 'json',
		method: 'POST', 
	    success: function (data) {
			alert('success') 
			$("#document-list").append(data.html),
			$("#new_document")[0].reset();
		},
		error: function (data) {
			alert('something went wrong') }
	})
})





</script>

app/views/documents/show.html.erb
<div id='document-show-container'>

    <div id='top'>
        <h1><%= @document.title %></h1>
        <div class='details-container'>
            <h3><%= @document.description %></h3>
            <h3 class='link'><a href="<%= @document.url %>" target="_blank">Go to Document</a></h3>

        	<h3>Last update: <%= format_date(@document.updated_at) %></h3>
            <td><%= link_to "Edit", edit_user_document_path(@document.user, @document) %></td>
            <td><%= link_to "Delete", user_document_path(@document.user, @document), :method => :delete %></td>
        </div>
    </div> <!-- close top -->

    <div id='bottom'>
        <div id='jobs' class='links-col-50 left-col-50'>
            <h2>LINKED JOBS</h2>
            <div class='linked-items'>
                <% if @document.jobs.length > 0 %>
                    <%= render partial: "jobs/job", collection: @document.jobs || "No Linked Jobs" %>
                <% else %>
                    <h3><%= link_to '* Link This Document To A Job', user_jobs_path(@document.user) %></h3>
                <% end %>
            </div>
        </div> <!-- close column -->

        <div id='tasks' class='links-col-50 right-col-50'>
            <h2>LINKED TASKS</h2>
            <div class='linked-items'>
                <% if @document.tasks.length > 0 %>
                    <%= render partial: "tasks/task", collection: @document.tasks || "No Linked Tasks" %>
                <% else %>
                    <h3><%= link_to '* Link This Document To A Task', user_tasks_path(@document.user) %></h3>

                <% end %>
            </div>
        </div> <!-- close column -->
    </div> <!-- close bottom -->

</div> <!-- close wrapper -->